// source: social_connect.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var social_pb = require('./social_pb.js');
goog.object.extend(proto, social_pb);
goog.exportSymbol('proto.SocialConnect.ClientApp', null, global);
goog.exportSymbol('proto.SocialConnect.ClientMetadata', null, global);
goog.exportSymbol('proto.SocialConnect.ConnectAdminRequest', null, global);
goog.exportSymbol('proto.SocialConnect.ConnectAdminResponse', null, global);
goog.exportSymbol('proto.SocialConnect.ConnectPublicRequest', null, global);
goog.exportSymbol('proto.SocialConnect.ConnectPublicResponse', null, global);
goog.exportSymbol('proto.SocialConnect.Error', null, global);
goog.exportSymbol('proto.SocialConnect.Grant', null, global);
goog.exportSymbol('proto.SocialConnect.GrantType', null, global);
goog.exportSymbol('proto.SocialConnect.Response', null, global);
goog.exportSymbol('proto.SocialConnect.ResponseType', null, global);
goog.exportSymbol('proto.SocialConnect.Scope', null, global);
goog.exportSymbol('proto.SocialConnect.ScopeType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SocialConnect.Scope = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SocialConnect.Scope, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SocialConnect.Scope.displayName = 'proto.SocialConnect.Scope';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SocialConnect.Grant = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SocialConnect.Grant, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SocialConnect.Grant.displayName = 'proto.SocialConnect.Grant';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SocialConnect.Response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SocialConnect.Response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SocialConnect.Response.displayName = 'proto.SocialConnect.Response';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SocialConnect.ClientMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SocialConnect.ClientMetadata.repeatedFields_, null);
};
goog.inherits(proto.SocialConnect.ClientMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SocialConnect.ClientMetadata.displayName = 'proto.SocialConnect.ClientMetadata';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SocialConnect.ClientApp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SocialConnect.ClientApp.repeatedFields_, null);
};
goog.inherits(proto.SocialConnect.ClientApp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SocialConnect.ClientApp.displayName = 'proto.SocialConnect.ClientApp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SocialConnect.ConnectPublicRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SocialConnect.ConnectPublicRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SocialConnect.ConnectPublicRequest.displayName = 'proto.SocialConnect.ConnectPublicRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SocialConnect.ConnectPublicResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SocialConnect.ConnectPublicResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SocialConnect.ConnectPublicResponse.displayName = 'proto.SocialConnect.ConnectPublicResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SocialConnect.ConnectAdminRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SocialConnect.ConnectAdminRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SocialConnect.ConnectAdminRequest.displayName = 'proto.SocialConnect.ConnectAdminRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SocialConnect.ConnectAdminResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SocialConnect.ConnectAdminResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SocialConnect.ConnectAdminResponse.displayName = 'proto.SocialConnect.ConnectAdminResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SocialConnect.Scope.prototype.toObject = function(opt_includeInstance) {
  return proto.SocialConnect.Scope.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SocialConnect.Scope} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocialConnect.Scope.toObject = function(includeInstance, msg) {
  var f, obj = {
    scopeType: jspb.Message.getFieldWithDefault(msg, 1, 0),
    readId: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    readEmail: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    readGender: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    readCreatedAt: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    offlineAccess: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    readName: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    readBirthday: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    readCountry: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    name: jspb.Message.getFieldWithDefault(msg, 10, ""),
    key: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SocialConnect.Scope}
 */
proto.SocialConnect.Scope.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SocialConnect.Scope;
  return proto.SocialConnect.Scope.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SocialConnect.Scope} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SocialConnect.Scope}
 */
proto.SocialConnect.Scope.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.SocialConnect.ScopeType} */ (reader.readEnum());
      msg.setScopeType(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReadId(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReadEmail(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReadGender(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReadCreatedAt(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOfflineAccess(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReadName(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReadBirthday(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReadCountry(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SocialConnect.Scope.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SocialConnect.Scope.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SocialConnect.Scope} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocialConnect.Scope.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getScopeType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getReadId();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getReadEmail();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getReadGender();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getReadCreatedAt();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getOfflineAccess();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getReadName();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getReadBirthday();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getReadCountry();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional ScopeType scope_type = 1;
 * @return {!proto.SocialConnect.ScopeType}
 */
proto.SocialConnect.Scope.prototype.getScopeType = function() {
  return /** @type {!proto.SocialConnect.ScopeType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.SocialConnect.ScopeType} value
 * @return {!proto.SocialConnect.Scope} returns this
 */
proto.SocialConnect.Scope.prototype.setScopeType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional bool read_id = 2;
 * @return {boolean}
 */
proto.SocialConnect.Scope.prototype.getReadId = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.SocialConnect.Scope} returns this
 */
proto.SocialConnect.Scope.prototype.setReadId = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool read_email = 3;
 * @return {boolean}
 */
proto.SocialConnect.Scope.prototype.getReadEmail = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.SocialConnect.Scope} returns this
 */
proto.SocialConnect.Scope.prototype.setReadEmail = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool read_gender = 4;
 * @return {boolean}
 */
proto.SocialConnect.Scope.prototype.getReadGender = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.SocialConnect.Scope} returns this
 */
proto.SocialConnect.Scope.prototype.setReadGender = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool read_created_at = 5;
 * @return {boolean}
 */
proto.SocialConnect.Scope.prototype.getReadCreatedAt = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.SocialConnect.Scope} returns this
 */
proto.SocialConnect.Scope.prototype.setReadCreatedAt = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool offline_access = 6;
 * @return {boolean}
 */
proto.SocialConnect.Scope.prototype.getOfflineAccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.SocialConnect.Scope} returns this
 */
proto.SocialConnect.Scope.prototype.setOfflineAccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool read_name = 7;
 * @return {boolean}
 */
proto.SocialConnect.Scope.prototype.getReadName = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.SocialConnect.Scope} returns this
 */
proto.SocialConnect.Scope.prototype.setReadName = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool read_birthday = 8;
 * @return {boolean}
 */
proto.SocialConnect.Scope.prototype.getReadBirthday = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.SocialConnect.Scope} returns this
 */
proto.SocialConnect.Scope.prototype.setReadBirthday = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional bool read_country = 9;
 * @return {boolean}
 */
proto.SocialConnect.Scope.prototype.getReadCountry = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.SocialConnect.Scope} returns this
 */
proto.SocialConnect.Scope.prototype.setReadCountry = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional string name = 10;
 * @return {string}
 */
proto.SocialConnect.Scope.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.Scope} returns this
 */
proto.SocialConnect.Scope.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string key = 11;
 * @return {string}
 */
proto.SocialConnect.Scope.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.Scope} returns this
 */
proto.SocialConnect.Scope.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SocialConnect.Grant.prototype.toObject = function(opt_includeInstance) {
  return proto.SocialConnect.Grant.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SocialConnect.Grant} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocialConnect.Grant.toObject = function(includeInstance, msg) {
  var f, obj = {
    grantType: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SocialConnect.Grant}
 */
proto.SocialConnect.Grant.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SocialConnect.Grant;
  return proto.SocialConnect.Grant.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SocialConnect.Grant} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SocialConnect.Grant}
 */
proto.SocialConnect.Grant.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.SocialConnect.GrantType} */ (reader.readEnum());
      msg.setGrantType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SocialConnect.Grant.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SocialConnect.Grant.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SocialConnect.Grant} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocialConnect.Grant.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGrantType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional GrantType grant_type = 1;
 * @return {!proto.SocialConnect.GrantType}
 */
proto.SocialConnect.Grant.prototype.getGrantType = function() {
  return /** @type {!proto.SocialConnect.GrantType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.SocialConnect.GrantType} value
 * @return {!proto.SocialConnect.Grant} returns this
 */
proto.SocialConnect.Grant.prototype.setGrantType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.SocialConnect.Grant.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.Grant} returns this
 */
proto.SocialConnect.Grant.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SocialConnect.Response.prototype.toObject = function(opt_includeInstance) {
  return proto.SocialConnect.Response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SocialConnect.Response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocialConnect.Response.toObject = function(includeInstance, msg) {
  var f, obj = {
    responseType: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SocialConnect.Response}
 */
proto.SocialConnect.Response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SocialConnect.Response;
  return proto.SocialConnect.Response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SocialConnect.Response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SocialConnect.Response}
 */
proto.SocialConnect.Response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.SocialConnect.ResponseType} */ (reader.readEnum());
      msg.setResponseType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SocialConnect.Response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SocialConnect.Response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SocialConnect.Response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocialConnect.Response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResponseType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional ResponseType response_type = 1;
 * @return {!proto.SocialConnect.ResponseType}
 */
proto.SocialConnect.Response.prototype.getResponseType = function() {
  return /** @type {!proto.SocialConnect.ResponseType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.SocialConnect.ResponseType} value
 * @return {!proto.SocialConnect.Response} returns this
 */
proto.SocialConnect.Response.prototype.setResponseType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.SocialConnect.Response.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.Response} returns this
 */
proto.SocialConnect.Response.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SocialConnect.ClientMetadata.repeatedFields_ = [21,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SocialConnect.ClientMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.SocialConnect.ClientMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SocialConnect.ClientMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocialConnect.ClientMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    isOpen: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    allowedEmailsList: (f = jspb.Message.getRepeatedField(msg, 21)) == null ? undefined : f,
    about: jspb.Message.getFieldWithDefault(msg, 3, ""),
    ownerId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    ageLowerLimit: jspb.Message.getFieldWithDefault(msg, 5, 0),
    ageUpperLimit: jspb.Message.getFieldWithDefault(msg, 6, 0),
    allowedCountriesList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    onlyVerifiedUsers: jspb.Message.getBooleanFieldWithDefault(msg, 8, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SocialConnect.ClientMetadata}
 */
proto.SocialConnect.ClientMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SocialConnect.ClientMetadata;
  return proto.SocialConnect.ClientMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SocialConnect.ClientMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SocialConnect.ClientMetadata}
 */
proto.SocialConnect.ClientMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsOpen(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.addAllowedEmails(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAbout(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwnerId(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAgeLowerLimit(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAgeUpperLimit(value);
      break;
    case 7:
      var values = /** @type {!Array<!proto.Social.CountryCode>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addAllowedCountries(values[i]);
      }
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOnlyVerifiedUsers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SocialConnect.ClientMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SocialConnect.ClientMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SocialConnect.ClientMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocialConnect.ClientMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIsOpen();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getAllowedEmailsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      21,
      f
    );
  }
  f = message.getAbout();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getOwnerId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAgeLowerLimit();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getAgeUpperLimit();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getAllowedCountriesList();
  if (f.length > 0) {
    writer.writePackedEnum(
      7,
      f
    );
  }
  f = message.getOnlyVerifiedUsers();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
};


/**
 * optional bool is_open = 1;
 * @return {boolean}
 */
proto.SocialConnect.ClientMetadata.prototype.getIsOpen = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.SocialConnect.ClientMetadata} returns this
 */
proto.SocialConnect.ClientMetadata.prototype.setIsOpen = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * repeated string allowed_emails = 21;
 * @return {!Array<string>}
 */
proto.SocialConnect.ClientMetadata.prototype.getAllowedEmailsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 21));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.SocialConnect.ClientMetadata} returns this
 */
proto.SocialConnect.ClientMetadata.prototype.setAllowedEmailsList = function(value) {
  return jspb.Message.setField(this, 21, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.SocialConnect.ClientMetadata} returns this
 */
proto.SocialConnect.ClientMetadata.prototype.addAllowedEmails = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 21, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SocialConnect.ClientMetadata} returns this
 */
proto.SocialConnect.ClientMetadata.prototype.clearAllowedEmailsList = function() {
  return this.setAllowedEmailsList([]);
};


/**
 * optional string about = 3;
 * @return {string}
 */
proto.SocialConnect.ClientMetadata.prototype.getAbout = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.ClientMetadata} returns this
 */
proto.SocialConnect.ClientMetadata.prototype.setAbout = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string owner_id = 4;
 * @return {string}
 */
proto.SocialConnect.ClientMetadata.prototype.getOwnerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.ClientMetadata} returns this
 */
proto.SocialConnect.ClientMetadata.prototype.setOwnerId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 age_lower_limit = 5;
 * @return {number}
 */
proto.SocialConnect.ClientMetadata.prototype.getAgeLowerLimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.SocialConnect.ClientMetadata} returns this
 */
proto.SocialConnect.ClientMetadata.prototype.setAgeLowerLimit = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 age_upper_limit = 6;
 * @return {number}
 */
proto.SocialConnect.ClientMetadata.prototype.getAgeUpperLimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.SocialConnect.ClientMetadata} returns this
 */
proto.SocialConnect.ClientMetadata.prototype.setAgeUpperLimit = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * repeated Social.CountryCode allowed_countries = 7;
 * @return {!Array<!proto.Social.CountryCode>}
 */
proto.SocialConnect.ClientMetadata.prototype.getAllowedCountriesList = function() {
  return /** @type {!Array<!proto.Social.CountryCode>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<!proto.Social.CountryCode>} value
 * @return {!proto.SocialConnect.ClientMetadata} returns this
 */
proto.SocialConnect.ClientMetadata.prototype.setAllowedCountriesList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {!proto.Social.CountryCode} value
 * @param {number=} opt_index
 * @return {!proto.SocialConnect.ClientMetadata} returns this
 */
proto.SocialConnect.ClientMetadata.prototype.addAllowedCountries = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SocialConnect.ClientMetadata} returns this
 */
proto.SocialConnect.ClientMetadata.prototype.clearAllowedCountriesList = function() {
  return this.setAllowedCountriesList([]);
};


/**
 * optional bool only_verified_users = 8;
 * @return {boolean}
 */
proto.SocialConnect.ClientMetadata.prototype.getOnlyVerifiedUsers = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.SocialConnect.ClientMetadata} returns this
 */
proto.SocialConnect.ClientMetadata.prototype.setOnlyVerifiedUsers = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SocialConnect.ClientApp.repeatedFields_ = [10,11,12,13,14,17,18,19,20];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SocialConnect.ClientApp.prototype.toObject = function(opt_includeInstance) {
  return proto.SocialConnect.ClientApp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SocialConnect.ClientApp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocialConnect.ClientApp.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    password: jspb.Message.getFieldWithDefault(msg, 3, ""),
    contactEmail: jspb.Message.getFieldWithDefault(msg, 4, ""),
    ownerId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    appWebsite: jspb.Message.getFieldWithDefault(msg, 6, ""),
    logoUrl: jspb.Message.getFieldWithDefault(msg, 7, ""),
    termsUrl: jspb.Message.getFieldWithDefault(msg, 8, ""),
    clientMetadata: (f = msg.getClientMetadata()) && proto.SocialConnect.ClientMetadata.toObject(includeInstance, f),
    audienceList: (f = jspb.Message.getRepeatedField(msg, 10)) == null ? undefined : f,
    scopesList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f,
    grantsList: (f = jspb.Message.getRepeatedField(msg, 12)) == null ? undefined : f,
    responsesList: (f = jspb.Message.getRepeatedField(msg, 13)) == null ? undefined : f,
    callbacksList: (f = jspb.Message.getRepeatedField(msg, 14)) == null ? undefined : f,
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    availableScopesList: jspb.Message.toObjectList(msg.getAvailableScopesList(),
    proto.SocialConnect.Scope.toObject, includeInstance),
    availableGrantsList: jspb.Message.toObjectList(msg.getAvailableGrantsList(),
    proto.SocialConnect.Grant.toObject, includeInstance),
    availableResponsesList: jspb.Message.toObjectList(msg.getAvailableResponsesList(),
    proto.SocialConnect.Response.toObject, includeInstance),
    availableCountriesList: jspb.Message.toObjectList(msg.getAvailableCountriesList(),
    social_pb.Country.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SocialConnect.ClientApp}
 */
proto.SocialConnect.ClientApp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SocialConnect.ClientApp;
  return proto.SocialConnect.ClientApp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SocialConnect.ClientApp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SocialConnect.ClientApp}
 */
proto.SocialConnect.ClientApp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setContactEmail(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwnerId(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setAppWebsite(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setLogoUrl(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setTermsUrl(value);
      break;
    case 9:
      var value = new proto.SocialConnect.ClientMetadata;
      reader.readMessage(value,proto.SocialConnect.ClientMetadata.deserializeBinaryFromReader);
      msg.setClientMetadata(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.addAudience(value);
      break;
    case 11:
      var values = /** @type {!Array<!proto.SocialConnect.ScopeType>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addScopes(values[i]);
      }
      break;
    case 12:
      var values = /** @type {!Array<!proto.SocialConnect.GrantType>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addGrants(values[i]);
      }
      break;
    case 13:
      var values = /** @type {!Array<!proto.SocialConnect.ResponseType>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addResponses(values[i]);
      }
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.addCallbacks(value);
      break;
    case 15:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 16:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 17:
      var value = new proto.SocialConnect.Scope;
      reader.readMessage(value,proto.SocialConnect.Scope.deserializeBinaryFromReader);
      msg.addAvailableScopes(value);
      break;
    case 18:
      var value = new proto.SocialConnect.Grant;
      reader.readMessage(value,proto.SocialConnect.Grant.deserializeBinaryFromReader);
      msg.addAvailableGrants(value);
      break;
    case 19:
      var value = new proto.SocialConnect.Response;
      reader.readMessage(value,proto.SocialConnect.Response.deserializeBinaryFromReader);
      msg.addAvailableResponses(value);
      break;
    case 20:
      var value = new social_pb.Country;
      reader.readMessage(value,social_pb.Country.deserializeBinaryFromReader);
      msg.addAvailableCountries(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SocialConnect.ClientApp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SocialConnect.ClientApp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SocialConnect.ClientApp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocialConnect.ClientApp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getContactEmail();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getOwnerId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getAppWebsite();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getLogoUrl();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getTermsUrl();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getClientMetadata();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.SocialConnect.ClientMetadata.serializeBinaryToWriter
    );
  }
  f = message.getAudienceList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      10,
      f
    );
  }
  f = message.getScopesList();
  if (f.length > 0) {
    writer.writePackedEnum(
      11,
      f
    );
  }
  f = message.getGrantsList();
  if (f.length > 0) {
    writer.writePackedEnum(
      12,
      f
    );
  }
  f = message.getResponsesList();
  if (f.length > 0) {
    writer.writePackedEnum(
      13,
      f
    );
  }
  f = message.getCallbacksList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      14,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getAvailableScopesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      17,
      f,
      proto.SocialConnect.Scope.serializeBinaryToWriter
    );
  }
  f = message.getAvailableGrantsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      18,
      f,
      proto.SocialConnect.Grant.serializeBinaryToWriter
    );
  }
  f = message.getAvailableResponsesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      19,
      f,
      proto.SocialConnect.Response.serializeBinaryToWriter
    );
  }
  f = message.getAvailableCountriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      20,
      f,
      social_pb.Country.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.SocialConnect.ClientApp.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.SocialConnect.ClientApp.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string password = 3;
 * @return {string}
 */
proto.SocialConnect.ClientApp.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string contact_email = 4;
 * @return {string}
 */
proto.SocialConnect.ClientApp.prototype.getContactEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.setContactEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string owner_id = 5;
 * @return {string}
 */
proto.SocialConnect.ClientApp.prototype.getOwnerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.setOwnerId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string app_website = 6;
 * @return {string}
 */
proto.SocialConnect.ClientApp.prototype.getAppWebsite = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.setAppWebsite = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string logo_url = 7;
 * @return {string}
 */
proto.SocialConnect.ClientApp.prototype.getLogoUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.setLogoUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string terms_url = 8;
 * @return {string}
 */
proto.SocialConnect.ClientApp.prototype.getTermsUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.setTermsUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional ClientMetadata client_metadata = 9;
 * @return {?proto.SocialConnect.ClientMetadata}
 */
proto.SocialConnect.ClientApp.prototype.getClientMetadata = function() {
  return /** @type{?proto.SocialConnect.ClientMetadata} */ (
    jspb.Message.getWrapperField(this, proto.SocialConnect.ClientMetadata, 9));
};


/**
 * @param {?proto.SocialConnect.ClientMetadata|undefined} value
 * @return {!proto.SocialConnect.ClientApp} returns this
*/
proto.SocialConnect.ClientApp.prototype.setClientMetadata = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.clearClientMetadata = function() {
  return this.setClientMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SocialConnect.ClientApp.prototype.hasClientMetadata = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * repeated string audience = 10;
 * @return {!Array<string>}
 */
proto.SocialConnect.ClientApp.prototype.getAudienceList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 10));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.setAudienceList = function(value) {
  return jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.addAudience = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.clearAudienceList = function() {
  return this.setAudienceList([]);
};


/**
 * repeated ScopeType scopes = 11;
 * @return {!Array<!proto.SocialConnect.ScopeType>}
 */
proto.SocialConnect.ClientApp.prototype.getScopesList = function() {
  return /** @type {!Array<!proto.SocialConnect.ScopeType>} */ (jspb.Message.getRepeatedField(this, 11));
};


/**
 * @param {!Array<!proto.SocialConnect.ScopeType>} value
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.setScopesList = function(value) {
  return jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {!proto.SocialConnect.ScopeType} value
 * @param {number=} opt_index
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.addScopes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.clearScopesList = function() {
  return this.setScopesList([]);
};


/**
 * repeated GrantType grants = 12;
 * @return {!Array<!proto.SocialConnect.GrantType>}
 */
proto.SocialConnect.ClientApp.prototype.getGrantsList = function() {
  return /** @type {!Array<!proto.SocialConnect.GrantType>} */ (jspb.Message.getRepeatedField(this, 12));
};


/**
 * @param {!Array<!proto.SocialConnect.GrantType>} value
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.setGrantsList = function(value) {
  return jspb.Message.setField(this, 12, value || []);
};


/**
 * @param {!proto.SocialConnect.GrantType} value
 * @param {number=} opt_index
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.addGrants = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 12, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.clearGrantsList = function() {
  return this.setGrantsList([]);
};


/**
 * repeated ResponseType responses = 13;
 * @return {!Array<!proto.SocialConnect.ResponseType>}
 */
proto.SocialConnect.ClientApp.prototype.getResponsesList = function() {
  return /** @type {!Array<!proto.SocialConnect.ResponseType>} */ (jspb.Message.getRepeatedField(this, 13));
};


/**
 * @param {!Array<!proto.SocialConnect.ResponseType>} value
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.setResponsesList = function(value) {
  return jspb.Message.setField(this, 13, value || []);
};


/**
 * @param {!proto.SocialConnect.ResponseType} value
 * @param {number=} opt_index
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.addResponses = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 13, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.clearResponsesList = function() {
  return this.setResponsesList([]);
};


/**
 * repeated string callbacks = 14;
 * @return {!Array<string>}
 */
proto.SocialConnect.ClientApp.prototype.getCallbacksList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 14));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.setCallbacksList = function(value) {
  return jspb.Message.setField(this, 14, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.addCallbacks = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 14, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.clearCallbacksList = function() {
  return this.setCallbacksList([]);
};


/**
 * optional google.protobuf.Timestamp created_at = 15;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.SocialConnect.ClientApp.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 15));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.SocialConnect.ClientApp} returns this
*/
proto.SocialConnect.ClientApp.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SocialConnect.ClientApp.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 16;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.SocialConnect.ClientApp.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 16));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.SocialConnect.ClientApp} returns this
*/
proto.SocialConnect.ClientApp.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SocialConnect.ClientApp.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * repeated Scope available_scopes = 17;
 * @return {!Array<!proto.SocialConnect.Scope>}
 */
proto.SocialConnect.ClientApp.prototype.getAvailableScopesList = function() {
  return /** @type{!Array<!proto.SocialConnect.Scope>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SocialConnect.Scope, 17));
};


/**
 * @param {!Array<!proto.SocialConnect.Scope>} value
 * @return {!proto.SocialConnect.ClientApp} returns this
*/
proto.SocialConnect.ClientApp.prototype.setAvailableScopesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 17, value);
};


/**
 * @param {!proto.SocialConnect.Scope=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SocialConnect.Scope}
 */
proto.SocialConnect.ClientApp.prototype.addAvailableScopes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 17, opt_value, proto.SocialConnect.Scope, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.clearAvailableScopesList = function() {
  return this.setAvailableScopesList([]);
};


/**
 * repeated Grant available_grants = 18;
 * @return {!Array<!proto.SocialConnect.Grant>}
 */
proto.SocialConnect.ClientApp.prototype.getAvailableGrantsList = function() {
  return /** @type{!Array<!proto.SocialConnect.Grant>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SocialConnect.Grant, 18));
};


/**
 * @param {!Array<!proto.SocialConnect.Grant>} value
 * @return {!proto.SocialConnect.ClientApp} returns this
*/
proto.SocialConnect.ClientApp.prototype.setAvailableGrantsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 18, value);
};


/**
 * @param {!proto.SocialConnect.Grant=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SocialConnect.Grant}
 */
proto.SocialConnect.ClientApp.prototype.addAvailableGrants = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 18, opt_value, proto.SocialConnect.Grant, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.clearAvailableGrantsList = function() {
  return this.setAvailableGrantsList([]);
};


/**
 * repeated Response available_responses = 19;
 * @return {!Array<!proto.SocialConnect.Response>}
 */
proto.SocialConnect.ClientApp.prototype.getAvailableResponsesList = function() {
  return /** @type{!Array<!proto.SocialConnect.Response>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SocialConnect.Response, 19));
};


/**
 * @param {!Array<!proto.SocialConnect.Response>} value
 * @return {!proto.SocialConnect.ClientApp} returns this
*/
proto.SocialConnect.ClientApp.prototype.setAvailableResponsesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 19, value);
};


/**
 * @param {!proto.SocialConnect.Response=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SocialConnect.Response}
 */
proto.SocialConnect.ClientApp.prototype.addAvailableResponses = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 19, opt_value, proto.SocialConnect.Response, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.clearAvailableResponsesList = function() {
  return this.setAvailableResponsesList([]);
};


/**
 * repeated Social.Country available_countries = 20;
 * @return {!Array<!proto.Social.Country>}
 */
proto.SocialConnect.ClientApp.prototype.getAvailableCountriesList = function() {
  return /** @type{!Array<!proto.Social.Country>} */ (
    jspb.Message.getRepeatedWrapperField(this, social_pb.Country, 20));
};


/**
 * @param {!Array<!proto.Social.Country>} value
 * @return {!proto.SocialConnect.ClientApp} returns this
*/
proto.SocialConnect.ClientApp.prototype.setAvailableCountriesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 20, value);
};


/**
 * @param {!proto.Social.Country=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Social.Country}
 */
proto.SocialConnect.ClientApp.prototype.addAvailableCountries = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 20, opt_value, proto.Social.Country, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SocialConnect.ClientApp} returns this
 */
proto.SocialConnect.ClientApp.prototype.clearAvailableCountriesList = function() {
  return this.setAvailableCountriesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SocialConnect.ConnectPublicRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.SocialConnect.ConnectPublicRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SocialConnect.ConnectPublicRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocialConnect.ConnectPublicRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    challenge: jspb.Message.getFieldWithDefault(msg, 1, ""),
    email: jspb.Message.getFieldWithDefault(msg, 2, ""),
    password: jspb.Message.getFieldWithDefault(msg, 3, ""),
    gender: jspb.Message.getFieldWithDefault(msg, 4, 0),
    consent: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    jwtVerificationToken: jspb.Message.getFieldWithDefault(msg, 6, ""),
    verificationProvider: (f = msg.getVerificationProvider()) && social_pb.VerificationProvider.toObject(includeInstance, f),
    authToken: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SocialConnect.ConnectPublicRequest}
 */
proto.SocialConnect.ConnectPublicRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SocialConnect.ConnectPublicRequest;
  return proto.SocialConnect.ConnectPublicRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SocialConnect.ConnectPublicRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SocialConnect.ConnectPublicRequest}
 */
proto.SocialConnect.ConnectPublicRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setChallenge(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    case 4:
      var value = /** @type {!proto.Social.Gender} */ (reader.readEnum());
      msg.setGender(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setConsent(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setJwtVerificationToken(value);
      break;
    case 7:
      var value = new social_pb.VerificationProvider;
      reader.readMessage(value,social_pb.VerificationProvider.deserializeBinaryFromReader);
      msg.setVerificationProvider(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthToken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SocialConnect.ConnectPublicRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SocialConnect.ConnectPublicRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SocialConnect.ConnectPublicRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocialConnect.ConnectPublicRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChallenge();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getGender();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getConsent();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getJwtVerificationToken();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getVerificationProvider();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      social_pb.VerificationProvider.serializeBinaryToWriter
    );
  }
  f = message.getAuthToken();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional string challenge = 1;
 * @return {string}
 */
proto.SocialConnect.ConnectPublicRequest.prototype.getChallenge = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.ConnectPublicRequest} returns this
 */
proto.SocialConnect.ConnectPublicRequest.prototype.setChallenge = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string email = 2;
 * @return {string}
 */
proto.SocialConnect.ConnectPublicRequest.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.ConnectPublicRequest} returns this
 */
proto.SocialConnect.ConnectPublicRequest.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string password = 3;
 * @return {string}
 */
proto.SocialConnect.ConnectPublicRequest.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.ConnectPublicRequest} returns this
 */
proto.SocialConnect.ConnectPublicRequest.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Social.Gender gender = 4;
 * @return {!proto.Social.Gender}
 */
proto.SocialConnect.ConnectPublicRequest.prototype.getGender = function() {
  return /** @type {!proto.Social.Gender} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.Social.Gender} value
 * @return {!proto.SocialConnect.ConnectPublicRequest} returns this
 */
proto.SocialConnect.ConnectPublicRequest.prototype.setGender = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional bool consent = 5;
 * @return {boolean}
 */
proto.SocialConnect.ConnectPublicRequest.prototype.getConsent = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.SocialConnect.ConnectPublicRequest} returns this
 */
proto.SocialConnect.ConnectPublicRequest.prototype.setConsent = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional string jwt_verification_token = 6;
 * @return {string}
 */
proto.SocialConnect.ConnectPublicRequest.prototype.getJwtVerificationToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.ConnectPublicRequest} returns this
 */
proto.SocialConnect.ConnectPublicRequest.prototype.setJwtVerificationToken = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional Social.VerificationProvider verification_provider = 7;
 * @return {?proto.Social.VerificationProvider}
 */
proto.SocialConnect.ConnectPublicRequest.prototype.getVerificationProvider = function() {
  return /** @type{?proto.Social.VerificationProvider} */ (
    jspb.Message.getWrapperField(this, social_pb.VerificationProvider, 7));
};


/**
 * @param {?proto.Social.VerificationProvider|undefined} value
 * @return {!proto.SocialConnect.ConnectPublicRequest} returns this
*/
proto.SocialConnect.ConnectPublicRequest.prototype.setVerificationProvider = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SocialConnect.ConnectPublicRequest} returns this
 */
proto.SocialConnect.ConnectPublicRequest.prototype.clearVerificationProvider = function() {
  return this.setVerificationProvider(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SocialConnect.ConnectPublicRequest.prototype.hasVerificationProvider = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string auth_token = 8;
 * @return {string}
 */
proto.SocialConnect.ConnectPublicRequest.prototype.getAuthToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.ConnectPublicRequest} returns this
 */
proto.SocialConnect.ConnectPublicRequest.prototype.setAuthToken = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SocialConnect.ConnectPublicResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.SocialConnect.ConnectPublicResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SocialConnect.ConnectPublicResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocialConnect.ConnectPublicResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    client: (f = msg.getClient()) && proto.SocialConnect.ClientApp.toObject(includeInstance, f),
    email: jspb.Message.getFieldWithDefault(msg, 2, ""),
    redirectAddr: jspb.Message.getFieldWithDefault(msg, 3, ""),
    error: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SocialConnect.ConnectPublicResponse}
 */
proto.SocialConnect.ConnectPublicResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SocialConnect.ConnectPublicResponse;
  return proto.SocialConnect.ConnectPublicResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SocialConnect.ConnectPublicResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SocialConnect.ConnectPublicResponse}
 */
proto.SocialConnect.ConnectPublicResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.SocialConnect.ClientApp;
      reader.readMessage(value,proto.SocialConnect.ClientApp.deserializeBinaryFromReader);
      msg.setClient(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRedirectAddr(value);
      break;
    case 4:
      var value = /** @type {!proto.SocialConnect.Error} */ (reader.readEnum());
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SocialConnect.ConnectPublicResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SocialConnect.ConnectPublicResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SocialConnect.ConnectPublicResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocialConnect.ConnectPublicResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClient();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.SocialConnect.ClientApp.serializeBinaryToWriter
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRedirectAddr();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getError();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
};


/**
 * optional ClientApp client = 1;
 * @return {?proto.SocialConnect.ClientApp}
 */
proto.SocialConnect.ConnectPublicResponse.prototype.getClient = function() {
  return /** @type{?proto.SocialConnect.ClientApp} */ (
    jspb.Message.getWrapperField(this, proto.SocialConnect.ClientApp, 1));
};


/**
 * @param {?proto.SocialConnect.ClientApp|undefined} value
 * @return {!proto.SocialConnect.ConnectPublicResponse} returns this
*/
proto.SocialConnect.ConnectPublicResponse.prototype.setClient = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SocialConnect.ConnectPublicResponse} returns this
 */
proto.SocialConnect.ConnectPublicResponse.prototype.clearClient = function() {
  return this.setClient(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SocialConnect.ConnectPublicResponse.prototype.hasClient = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string email = 2;
 * @return {string}
 */
proto.SocialConnect.ConnectPublicResponse.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.ConnectPublicResponse} returns this
 */
proto.SocialConnect.ConnectPublicResponse.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string redirect_addr = 3;
 * @return {string}
 */
proto.SocialConnect.ConnectPublicResponse.prototype.getRedirectAddr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.SocialConnect.ConnectPublicResponse} returns this
 */
proto.SocialConnect.ConnectPublicResponse.prototype.setRedirectAddr = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Error error = 4;
 * @return {!proto.SocialConnect.Error}
 */
proto.SocialConnect.ConnectPublicResponse.prototype.getError = function() {
  return /** @type {!proto.SocialConnect.Error} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.SocialConnect.Error} value
 * @return {!proto.SocialConnect.ConnectPublicResponse} returns this
 */
proto.SocialConnect.ConnectPublicResponse.prototype.setError = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SocialConnect.ConnectAdminRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.SocialConnect.ConnectAdminRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SocialConnect.ConnectAdminRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocialConnect.ConnectAdminRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    app: (f = msg.getApp()) && proto.SocialConnect.ClientApp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SocialConnect.ConnectAdminRequest}
 */
proto.SocialConnect.ConnectAdminRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SocialConnect.ConnectAdminRequest;
  return proto.SocialConnect.ConnectAdminRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SocialConnect.ConnectAdminRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SocialConnect.ConnectAdminRequest}
 */
proto.SocialConnect.ConnectAdminRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.SocialConnect.ClientApp;
      reader.readMessage(value,proto.SocialConnect.ClientApp.deserializeBinaryFromReader);
      msg.setApp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SocialConnect.ConnectAdminRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SocialConnect.ConnectAdminRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SocialConnect.ConnectAdminRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocialConnect.ConnectAdminRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getApp();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.SocialConnect.ClientApp.serializeBinaryToWriter
    );
  }
};


/**
 * optional ClientApp app = 1;
 * @return {?proto.SocialConnect.ClientApp}
 */
proto.SocialConnect.ConnectAdminRequest.prototype.getApp = function() {
  return /** @type{?proto.SocialConnect.ClientApp} */ (
    jspb.Message.getWrapperField(this, proto.SocialConnect.ClientApp, 1));
};


/**
 * @param {?proto.SocialConnect.ClientApp|undefined} value
 * @return {!proto.SocialConnect.ConnectAdminRequest} returns this
*/
proto.SocialConnect.ConnectAdminRequest.prototype.setApp = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SocialConnect.ConnectAdminRequest} returns this
 */
proto.SocialConnect.ConnectAdminRequest.prototype.clearApp = function() {
  return this.setApp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SocialConnect.ConnectAdminRequest.prototype.hasApp = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SocialConnect.ConnectAdminResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.SocialConnect.ConnectAdminResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SocialConnect.ConnectAdminResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocialConnect.ConnectAdminResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    app: (f = msg.getApp()) && proto.SocialConnect.ClientApp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SocialConnect.ConnectAdminResponse}
 */
proto.SocialConnect.ConnectAdminResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SocialConnect.ConnectAdminResponse;
  return proto.SocialConnect.ConnectAdminResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SocialConnect.ConnectAdminResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SocialConnect.ConnectAdminResponse}
 */
proto.SocialConnect.ConnectAdminResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.SocialConnect.ClientApp;
      reader.readMessage(value,proto.SocialConnect.ClientApp.deserializeBinaryFromReader);
      msg.setApp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SocialConnect.ConnectAdminResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SocialConnect.ConnectAdminResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SocialConnect.ConnectAdminResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocialConnect.ConnectAdminResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getApp();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.SocialConnect.ClientApp.serializeBinaryToWriter
    );
  }
};


/**
 * optional ClientApp app = 1;
 * @return {?proto.SocialConnect.ClientApp}
 */
proto.SocialConnect.ConnectAdminResponse.prototype.getApp = function() {
  return /** @type{?proto.SocialConnect.ClientApp} */ (
    jspb.Message.getWrapperField(this, proto.SocialConnect.ClientApp, 1));
};


/**
 * @param {?proto.SocialConnect.ClientApp|undefined} value
 * @return {!proto.SocialConnect.ConnectAdminResponse} returns this
*/
proto.SocialConnect.ConnectAdminResponse.prototype.setApp = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SocialConnect.ConnectAdminResponse} returns this
 */
proto.SocialConnect.ConnectAdminResponse.prototype.clearApp = function() {
  return this.setApp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SocialConnect.ConnectAdminResponse.prototype.hasApp = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * @enum {number}
 */
proto.SocialConnect.Error = {
  NO_ERROR: 0,
  ERROR_REQUIRE_IDENTIFICATION: 1
};

/**
 * @enum {number}
 */
proto.SocialConnect.ScopeType = {
  INVALID_SCOPE: 0,
  DEFAULT_SCOPE: 1,
  OFFLINE_ACCESS_SCOPE: 2,
  GENDER_SCOPE: 3,
  NAME_SCOPE: 4,
  BIRTHDAY_SCOPE: 5,
  COUNTRY_SCOPE: 6,
  EMAIL_SCOPE: 7
};

/**
 * @enum {number}
 */
proto.SocialConnect.GrantType = {
  INVALID_GRANT: 0,
  AUTH_GRANT: 1,
  REFRESH_GRANT: 2
};

/**
 * @enum {number}
 */
proto.SocialConnect.ResponseType = {
  INVALID_RESPONSE: 0,
  CODE_RESPONSE: 1,
  TOKEN_RESPONSE: 2,
  ID_RESPONSE: 3
};

goog.object.extend(exports, proto.SocialConnect);
