// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: nuntio.proto

package go_nuntio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountryCode int32

const (
	CountryCode_INVALID_COUNTRY CountryCode = 0
	CountryCode_COUTRY_DK       CountryCode = 1
	CountryCode_COUNTRY_NO      CountryCode = 2
	CountryCode_COUNTRY_DE      CountryCode = 3
)

// Enum value maps for CountryCode.
var (
	CountryCode_name = map[int32]string{
		0: "INVALID_COUNTRY",
		1: "COUTRY_DK",
		2: "COUNTRY_NO",
		3: "COUNTRY_DE",
	}
	CountryCode_value = map[string]int32{
		"INVALID_COUNTRY": 0,
		"COUTRY_DK":       1,
		"COUNTRY_NO":      2,
		"COUNTRY_DE":      3,
	}
)

func (x CountryCode) Enum() *CountryCode {
	p := new(CountryCode)
	*p = x
	return p
}

func (x CountryCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CountryCode) Descriptor() protoreflect.EnumDescriptor {
	return file_nuntio_proto_enumTypes[0].Descriptor()
}

func (CountryCode) Type() protoreflect.EnumType {
	return &file_nuntio_proto_enumTypes[0]
}

func (x CountryCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CountryCode.Descriptor instead.
func (CountryCode) EnumDescriptor() ([]byte, []int) {
	return file_nuntio_proto_rawDescGZIP(), []int{0}
}

type Gender int32

const (
	Gender_INVALID_GENDER Gender = 0
	Gender_MALE           Gender = 1
	Gender_FEMALE         Gender = 2
	Gender_OTHER          Gender = 3
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "INVALID_GENDER",
		1: "MALE",
		2: "FEMALE",
		3: "OTHER",
	}
	Gender_value = map[string]int32{
		"INVALID_GENDER": 0,
		"MALE":           1,
		"FEMALE":         2,
		"OTHER":          3,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_nuntio_proto_enumTypes[1].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_nuntio_proto_enumTypes[1]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_nuntio_proto_rawDescGZIP(), []int{1}
}

type VerificationProviderType int32

const (
	VerificationProviderType_INVALID VerificationProviderType = 0
	VerificationProviderType_MIT_ID  VerificationProviderType = 1
)

// Enum value maps for VerificationProviderType.
var (
	VerificationProviderType_name = map[int32]string{
		0: "INVALID",
		1: "MIT_ID",
	}
	VerificationProviderType_value = map[string]int32{
		"INVALID": 0,
		"MIT_ID":  1,
	}
)

func (x VerificationProviderType) Enum() *VerificationProviderType {
	p := new(VerificationProviderType)
	*p = x
	return p
}

func (x VerificationProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerificationProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_nuntio_proto_enumTypes[2].Descriptor()
}

func (VerificationProviderType) Type() protoreflect.EnumType {
	return &file_nuntio_proto_enumTypes[2]
}

func (x VerificationProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerificationProviderType.Descriptor instead.
func (VerificationProviderType) EnumDescriptor() ([]byte, []int) {
	return file_nuntio_proto_rawDescGZIP(), []int{2}
}

type ErrorType int32

const (
	ErrorType_NO_ERROR                    ErrorType = 0
	ErrorType_CONNECT_ONLY_VERIFIED       ErrorType = 1
	ErrorType_CONNCET_AGE_LOWER_BROKEN    ErrorType = 2
	ErrorType_CONNCET_AGE_UPPER_BROKEN    ErrorType = 3
	ErrorType_CONNCET_COUNTRY_NOT_ALLOWED ErrorType = 4
	ErrorType_CONNECT_IS_NOT_OPEN         ErrorType = 5
	ErrorType_CONNECT_WEAK_PASSWORD       ErrorType = 6
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0: "NO_ERROR",
		1: "CONNECT_ONLY_VERIFIED",
		2: "CONNCET_AGE_LOWER_BROKEN",
		3: "CONNCET_AGE_UPPER_BROKEN",
		4: "CONNCET_COUNTRY_NOT_ALLOWED",
		5: "CONNECT_IS_NOT_OPEN",
		6: "CONNECT_WEAK_PASSWORD",
	}
	ErrorType_value = map[string]int32{
		"NO_ERROR":                    0,
		"CONNECT_ONLY_VERIFIED":       1,
		"CONNCET_AGE_LOWER_BROKEN":    2,
		"CONNCET_AGE_UPPER_BROKEN":    3,
		"CONNCET_COUNTRY_NOT_ALLOWED": 4,
		"CONNECT_IS_NOT_OPEN":         5,
		"CONNECT_WEAK_PASSWORD":       6,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_nuntio_proto_enumTypes[3].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_nuntio_proto_enumTypes[3]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorType.Descriptor instead.
func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_nuntio_proto_rawDescGZIP(), []int{3}
}

type VerificationProvider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type VerificationProviderType `protobuf:"varint,1,opt,name=type,proto3,enum=Nuntio.VerificationProviderType" json:"type,omitempty"`
	Name string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *VerificationProvider) Reset() {
	*x = VerificationProvider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nuntio_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationProvider) ProtoMessage() {}

func (x *VerificationProvider) ProtoReflect() protoreflect.Message {
	mi := &file_nuntio_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationProvider.ProtoReflect.Descriptor instead.
func (*VerificationProvider) Descriptor() ([]byte, []int) {
	return file_nuntio_proto_rawDescGZIP(), []int{0}
}

func (x *VerificationProvider) GetType() VerificationProviderType {
	if x != nil {
		return x.Type
	}
	return VerificationProviderType_INVALID
}

func (x *VerificationProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Country struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryCode CountryCode `protobuf:"varint,1,opt,name=country_code,json=countryCode,proto3,enum=Nuntio.CountryCode" json:"country_code,omitempty"`
	Name        string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Country) Reset() {
	*x = Country{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nuntio_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_nuntio_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_nuntio_proto_rawDescGZIP(), []int{1}
}

func (x *Country) GetCountryCode() CountryCode {
	if x != nil {
		return x.CountryCode
	}
	return CountryCode_INVALID_COUNTRY
}

func (x *Country) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   ErrorType `protobuf:"varint,1,opt,name=error,proto3,enum=Nuntio.ErrorType" json:"error,omitempty"`
	Message string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nuntio_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_nuntio_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_nuntio_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetError() ErrorType {
	if x != nil {
		return x.Error
	}
	return ErrorType_NO_ERROR
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_nuntio_proto protoreflect.FileDescriptor

var file_nuntio_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6e, 0x75, 0x6e, 0x74, 0x69, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x4e, 0x75, 0x6e, 0x74, 0x69, 0x6f, 0x22, 0x60, 0x0a, 0x14, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x34,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x4e,
	0x75, 0x6e, 0x74, 0x69, 0x6f, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x55, 0x0a, 0x07, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x36, 0x0a, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x4e, 0x75, 0x6e, 0x74,
	0x69, 0x6f, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0b,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x4a, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x27, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x4e, 0x75, 0x6e, 0x74, 0x69, 0x6f,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x51, 0x0a, 0x0b, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x4e,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x52, 0x59, 0x10, 0x00, 0x12,
	0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x55, 0x54, 0x52, 0x59, 0x5f, 0x44, 0x4b, 0x10, 0x01, 0x12, 0x0e,
	0x0a, 0x0a, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x52, 0x59, 0x5f, 0x4e, 0x4f, 0x10, 0x02, 0x12, 0x0e,
	0x0a, 0x0a, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x52, 0x59, 0x5f, 0x44, 0x45, 0x10, 0x03, 0x2a, 0x3d,
	0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x47, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x45, 0x4d, 0x41, 0x4c, 0x45,
	0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x03, 0x2a, 0x33, 0x0a,
	0x18, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x49, 0x54, 0x5f, 0x49, 0x44,
	0x10, 0x01, 0x2a, 0xc5, 0x01, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x19,
	0x0a, 0x15, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x5f, 0x4f, 0x4e, 0x4c, 0x59, 0x5f, 0x56,
	0x45, 0x52, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x43, 0x4f, 0x4e,
	0x4e, 0x43, 0x45, 0x54, 0x5f, 0x41, 0x47, 0x45, 0x5f, 0x4c, 0x4f, 0x57, 0x45, 0x52, 0x5f, 0x42,
	0x52, 0x4f, 0x4b, 0x45, 0x4e, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x43, 0x4f, 0x4e, 0x4e, 0x43,
	0x45, 0x54, 0x5f, 0x41, 0x47, 0x45, 0x5f, 0x55, 0x50, 0x50, 0x45, 0x52, 0x5f, 0x42, 0x52, 0x4f,
	0x4b, 0x45, 0x4e, 0x10, 0x03, 0x12, 0x1f, 0x0a, 0x1b, 0x43, 0x4f, 0x4e, 0x4e, 0x43, 0x45, 0x54,
	0x5f, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x52, 0x59, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x4c, 0x4c,
	0x4f, 0x57, 0x45, 0x44, 0x10, 0x04, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43,
	0x54, 0x5f, 0x49, 0x53, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x05, 0x12,
	0x19, 0x0a, 0x15, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x5f, 0x57, 0x45, 0x41, 0x4b, 0x5f,
	0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x10, 0x06, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f,
	0x67, 0x6f, 0x5f, 0x6e, 0x75, 0x6e, 0x74, 0x69, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_nuntio_proto_rawDescOnce sync.Once
	file_nuntio_proto_rawDescData = file_nuntio_proto_rawDesc
)

func file_nuntio_proto_rawDescGZIP() []byte {
	file_nuntio_proto_rawDescOnce.Do(func() {
		file_nuntio_proto_rawDescData = protoimpl.X.CompressGZIP(file_nuntio_proto_rawDescData)
	})
	return file_nuntio_proto_rawDescData
}

var file_nuntio_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_nuntio_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nuntio_proto_goTypes = []interface{}{
	(CountryCode)(0),              // 0: Nuntio.CountryCode
	(Gender)(0),                   // 1: Nuntio.Gender
	(VerificationProviderType)(0), // 2: Nuntio.VerificationProviderType
	(ErrorType)(0),                // 3: Nuntio.ErrorType
	(*VerificationProvider)(nil),  // 4: Nuntio.VerificationProvider
	(*Country)(nil),               // 5: Nuntio.Country
	(*Error)(nil),                 // 6: Nuntio.Error
}
var file_nuntio_proto_depIdxs = []int32{
	2, // 0: Nuntio.VerificationProvider.type:type_name -> Nuntio.VerificationProviderType
	0, // 1: Nuntio.Country.country_code:type_name -> Nuntio.CountryCode
	3, // 2: Nuntio.Error.error:type_name -> Nuntio.ErrorType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nuntio_proto_init() }
func file_nuntio_proto_init() {
	if File_nuntio_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nuntio_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationProvider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nuntio_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Country); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nuntio_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nuntio_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nuntio_proto_goTypes,
		DependencyIndexes: file_nuntio_proto_depIdxs,
		EnumInfos:         file_nuntio_proto_enumTypes,
		MessageInfos:      file_nuntio_proto_msgTypes,
	}.Build()
	File_nuntio_proto = out.File
	file_nuntio_proto_rawDesc = nil
	file_nuntio_proto_goTypes = nil
	file_nuntio_proto_depIdxs = nil
}
