// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package go_nuntio

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PublicConnectServiceClient is the client API for PublicConnectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicConnectServiceClient interface {
	Heartbeat(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error)
	ValidateLoginChallenge(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error)
	Login(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error)
	ValidateConsentChallenge(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error)
	GiveConsent(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error)
	Logout(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error)
	CreateUser(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error)
	SendResetEmail(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error)
	ResetPassword(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error)
	Verify(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error)
}

type publicConnectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicConnectServiceClient(cc grpc.ClientConnInterface) PublicConnectServiceClient {
	return &publicConnectServiceClient{cc}
}

func (c *publicConnectServiceClient) Heartbeat(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error) {
	out := new(ConnectPublicResponse)
	err := c.cc.Invoke(ctx, "/NuntioConnect.PublicConnectService/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicConnectServiceClient) ValidateLoginChallenge(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error) {
	out := new(ConnectPublicResponse)
	err := c.cc.Invoke(ctx, "/NuntioConnect.PublicConnectService/ValidateLoginChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicConnectServiceClient) Login(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error) {
	out := new(ConnectPublicResponse)
	err := c.cc.Invoke(ctx, "/NuntioConnect.PublicConnectService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicConnectServiceClient) ValidateConsentChallenge(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error) {
	out := new(ConnectPublicResponse)
	err := c.cc.Invoke(ctx, "/NuntioConnect.PublicConnectService/ValidateConsentChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicConnectServiceClient) GiveConsent(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error) {
	out := new(ConnectPublicResponse)
	err := c.cc.Invoke(ctx, "/NuntioConnect.PublicConnectService/GiveConsent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicConnectServiceClient) Logout(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error) {
	out := new(ConnectPublicResponse)
	err := c.cc.Invoke(ctx, "/NuntioConnect.PublicConnectService/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicConnectServiceClient) CreateUser(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error) {
	out := new(ConnectPublicResponse)
	err := c.cc.Invoke(ctx, "/NuntioConnect.PublicConnectService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicConnectServiceClient) SendResetEmail(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error) {
	out := new(ConnectPublicResponse)
	err := c.cc.Invoke(ctx, "/NuntioConnect.PublicConnectService/SendResetEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicConnectServiceClient) ResetPassword(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error) {
	out := new(ConnectPublicResponse)
	err := c.cc.Invoke(ctx, "/NuntioConnect.PublicConnectService/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicConnectServiceClient) Verify(ctx context.Context, in *ConnectPublicRequest, opts ...grpc.CallOption) (*ConnectPublicResponse, error) {
	out := new(ConnectPublicResponse)
	err := c.cc.Invoke(ctx, "/NuntioConnect.PublicConnectService/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicConnectServiceServer is the server API for PublicConnectService service.
// All implementations should embed UnimplementedPublicConnectServiceServer
// for forward compatibility
type PublicConnectServiceServer interface {
	Heartbeat(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error)
	ValidateLoginChallenge(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error)
	Login(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error)
	ValidateConsentChallenge(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error)
	GiveConsent(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error)
	Logout(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error)
	CreateUser(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error)
	SendResetEmail(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error)
	ResetPassword(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error)
	Verify(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error)
}

// UnimplementedPublicConnectServiceServer should be embedded to have forward compatible implementations.
type UnimplementedPublicConnectServiceServer struct {
}

func (UnimplementedPublicConnectServiceServer) Heartbeat(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedPublicConnectServiceServer) ValidateLoginChallenge(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateLoginChallenge not implemented")
}
func (UnimplementedPublicConnectServiceServer) Login(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedPublicConnectServiceServer) ValidateConsentChallenge(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateConsentChallenge not implemented")
}
func (UnimplementedPublicConnectServiceServer) GiveConsent(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GiveConsent not implemented")
}
func (UnimplementedPublicConnectServiceServer) Logout(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedPublicConnectServiceServer) CreateUser(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedPublicConnectServiceServer) SendResetEmail(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendResetEmail not implemented")
}
func (UnimplementedPublicConnectServiceServer) ResetPassword(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPassword not implemented")
}
func (UnimplementedPublicConnectServiceServer) Verify(context.Context, *ConnectPublicRequest) (*ConnectPublicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}

// UnsafePublicConnectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicConnectServiceServer will
// result in compilation errors.
type UnsafePublicConnectServiceServer interface {
	mustEmbedUnimplementedPublicConnectServiceServer()
}

func RegisterPublicConnectServiceServer(s grpc.ServiceRegistrar, srv PublicConnectServiceServer) {
	s.RegisterService(&PublicConnectService_ServiceDesc, srv)
}

func _PublicConnectService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPublicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicConnectServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NuntioConnect.PublicConnectService/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicConnectServiceServer).Heartbeat(ctx, req.(*ConnectPublicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicConnectService_ValidateLoginChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPublicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicConnectServiceServer).ValidateLoginChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NuntioConnect.PublicConnectService/ValidateLoginChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicConnectServiceServer).ValidateLoginChallenge(ctx, req.(*ConnectPublicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicConnectService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPublicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicConnectServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NuntioConnect.PublicConnectService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicConnectServiceServer).Login(ctx, req.(*ConnectPublicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicConnectService_ValidateConsentChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPublicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicConnectServiceServer).ValidateConsentChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NuntioConnect.PublicConnectService/ValidateConsentChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicConnectServiceServer).ValidateConsentChallenge(ctx, req.(*ConnectPublicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicConnectService_GiveConsent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPublicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicConnectServiceServer).GiveConsent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NuntioConnect.PublicConnectService/GiveConsent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicConnectServiceServer).GiveConsent(ctx, req.(*ConnectPublicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicConnectService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPublicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicConnectServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NuntioConnect.PublicConnectService/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicConnectServiceServer).Logout(ctx, req.(*ConnectPublicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicConnectService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPublicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicConnectServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NuntioConnect.PublicConnectService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicConnectServiceServer).CreateUser(ctx, req.(*ConnectPublicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicConnectService_SendResetEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPublicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicConnectServiceServer).SendResetEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NuntioConnect.PublicConnectService/SendResetEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicConnectServiceServer).SendResetEmail(ctx, req.(*ConnectPublicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicConnectService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPublicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicConnectServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NuntioConnect.PublicConnectService/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicConnectServiceServer).ResetPassword(ctx, req.(*ConnectPublicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicConnectService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPublicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicConnectServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NuntioConnect.PublicConnectService/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicConnectServiceServer).Verify(ctx, req.(*ConnectPublicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicConnectService_ServiceDesc is the grpc.ServiceDesc for PublicConnectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicConnectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NuntioConnect.PublicConnectService",
	HandlerType: (*PublicConnectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _PublicConnectService_Heartbeat_Handler,
		},
		{
			MethodName: "ValidateLoginChallenge",
			Handler:    _PublicConnectService_ValidateLoginChallenge_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _PublicConnectService_Login_Handler,
		},
		{
			MethodName: "ValidateConsentChallenge",
			Handler:    _PublicConnectService_ValidateConsentChallenge_Handler,
		},
		{
			MethodName: "GiveConsent",
			Handler:    _PublicConnectService_GiveConsent_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _PublicConnectService_Logout_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _PublicConnectService_CreateUser_Handler,
		},
		{
			MethodName: "SendResetEmail",
			Handler:    _PublicConnectService_SendResetEmail_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _PublicConnectService_ResetPassword_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _PublicConnectService_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nuntio_connect.proto",
}

// AdminConnectServiceClient is the client API for AdminConnectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminConnectServiceClient interface {
	Heartbeat(ctx context.Context, in *ConnectAdminRequest, opts ...grpc.CallOption) (*ConnectAdminResponse, error)
	Create(ctx context.Context, in *ConnectAdminRequest, opts ...grpc.CallOption) (*ConnectAdminResponse, error)
	GetById(ctx context.Context, in *ConnectAdminRequest, opts ...grpc.CallOption) (*ConnectAdminResponse, error)
	UpdateDetails(ctx context.Context, in *ConnectAdminRequest, opts ...grpc.CallOption) (*ConnectAdminResponse, error)
	UpdateOauth(ctx context.Context, in *ConnectAdminRequest, opts ...grpc.CallOption) (*ConnectAdminResponse, error)
	Delete(ctx context.Context, in *ConnectAdminRequest, opts ...grpc.CallOption) (*ConnectAdminResponse, error)
}

type adminConnectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminConnectServiceClient(cc grpc.ClientConnInterface) AdminConnectServiceClient {
	return &adminConnectServiceClient{cc}
}

func (c *adminConnectServiceClient) Heartbeat(ctx context.Context, in *ConnectAdminRequest, opts ...grpc.CallOption) (*ConnectAdminResponse, error) {
	out := new(ConnectAdminResponse)
	err := c.cc.Invoke(ctx, "/NuntioConnect.AdminConnectService/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminConnectServiceClient) Create(ctx context.Context, in *ConnectAdminRequest, opts ...grpc.CallOption) (*ConnectAdminResponse, error) {
	out := new(ConnectAdminResponse)
	err := c.cc.Invoke(ctx, "/NuntioConnect.AdminConnectService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminConnectServiceClient) GetById(ctx context.Context, in *ConnectAdminRequest, opts ...grpc.CallOption) (*ConnectAdminResponse, error) {
	out := new(ConnectAdminResponse)
	err := c.cc.Invoke(ctx, "/NuntioConnect.AdminConnectService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminConnectServiceClient) UpdateDetails(ctx context.Context, in *ConnectAdminRequest, opts ...grpc.CallOption) (*ConnectAdminResponse, error) {
	out := new(ConnectAdminResponse)
	err := c.cc.Invoke(ctx, "/NuntioConnect.AdminConnectService/UpdateDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminConnectServiceClient) UpdateOauth(ctx context.Context, in *ConnectAdminRequest, opts ...grpc.CallOption) (*ConnectAdminResponse, error) {
	out := new(ConnectAdminResponse)
	err := c.cc.Invoke(ctx, "/NuntioConnect.AdminConnectService/UpdateOauth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminConnectServiceClient) Delete(ctx context.Context, in *ConnectAdminRequest, opts ...grpc.CallOption) (*ConnectAdminResponse, error) {
	out := new(ConnectAdminResponse)
	err := c.cc.Invoke(ctx, "/NuntioConnect.AdminConnectService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminConnectServiceServer is the server API for AdminConnectService service.
// All implementations should embed UnimplementedAdminConnectServiceServer
// for forward compatibility
type AdminConnectServiceServer interface {
	Heartbeat(context.Context, *ConnectAdminRequest) (*ConnectAdminResponse, error)
	Create(context.Context, *ConnectAdminRequest) (*ConnectAdminResponse, error)
	GetById(context.Context, *ConnectAdminRequest) (*ConnectAdminResponse, error)
	UpdateDetails(context.Context, *ConnectAdminRequest) (*ConnectAdminResponse, error)
	UpdateOauth(context.Context, *ConnectAdminRequest) (*ConnectAdminResponse, error)
	Delete(context.Context, *ConnectAdminRequest) (*ConnectAdminResponse, error)
}

// UnimplementedAdminConnectServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAdminConnectServiceServer struct {
}

func (UnimplementedAdminConnectServiceServer) Heartbeat(context.Context, *ConnectAdminRequest) (*ConnectAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAdminConnectServiceServer) Create(context.Context, *ConnectAdminRequest) (*ConnectAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAdminConnectServiceServer) GetById(context.Context, *ConnectAdminRequest) (*ConnectAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedAdminConnectServiceServer) UpdateDetails(context.Context, *ConnectAdminRequest) (*ConnectAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDetails not implemented")
}
func (UnimplementedAdminConnectServiceServer) UpdateOauth(context.Context, *ConnectAdminRequest) (*ConnectAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOauth not implemented")
}
func (UnimplementedAdminConnectServiceServer) Delete(context.Context, *ConnectAdminRequest) (*ConnectAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

// UnsafeAdminConnectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminConnectServiceServer will
// result in compilation errors.
type UnsafeAdminConnectServiceServer interface {
	mustEmbedUnimplementedAdminConnectServiceServer()
}

func RegisterAdminConnectServiceServer(s grpc.ServiceRegistrar, srv AdminConnectServiceServer) {
	s.RegisterService(&AdminConnectService_ServiceDesc, srv)
}

func _AdminConnectService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConnectServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NuntioConnect.AdminConnectService/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConnectServiceServer).Heartbeat(ctx, req.(*ConnectAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminConnectService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConnectServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NuntioConnect.AdminConnectService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConnectServiceServer).Create(ctx, req.(*ConnectAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminConnectService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConnectServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NuntioConnect.AdminConnectService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConnectServiceServer).GetById(ctx, req.(*ConnectAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminConnectService_UpdateDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConnectServiceServer).UpdateDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NuntioConnect.AdminConnectService/UpdateDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConnectServiceServer).UpdateDetails(ctx, req.(*ConnectAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminConnectService_UpdateOauth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConnectServiceServer).UpdateOauth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NuntioConnect.AdminConnectService/UpdateOauth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConnectServiceServer).UpdateOauth(ctx, req.(*ConnectAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminConnectService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConnectServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NuntioConnect.AdminConnectService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConnectServiceServer).Delete(ctx, req.(*ConnectAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminConnectService_ServiceDesc is the grpc.ServiceDesc for AdminConnectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminConnectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NuntioConnect.AdminConnectService",
	HandlerType: (*AdminConnectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _AdminConnectService_Heartbeat_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AdminConnectService_Create_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _AdminConnectService_GetById_Handler,
		},
		{
			MethodName: "UpdateDetails",
			Handler:    _AdminConnectService_UpdateDetails_Handler,
		},
		{
			MethodName: "UpdateOauth",
			Handler:    _AdminConnectService_UpdateOauth_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AdminConnectService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nuntio_connect.proto",
}
